<a href="https://colab.research.google.com/github/AshlinShaji/DL/blob/main/image_classification_SVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [48]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [49]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os #directory file path define
from sklearn.svm import SVC
from skimage.io import imread #to read image
from sklearn.model_selection import train_test_split
from skimage.transform import resize

In [50]:
os.listdir('/content/drive/MyDrive/Data_cnn')

['Cat', 'Dog']

In [51]:
os.listdir('/content/drive/MyDrive/Data_cnn/Cat')

['cat.82.jpg',
 'cat.48.jpg',
 'cat.67.jpg',
 'cat.97.jpg',
 'cat.103.jpg',
 'cat.56.jpg',
 'cat.69.jpg',
 'cat.94.jpg',
 'cat.80.jpg',
 'cat.86.jpg',
 'cat.39.jpg',
 'cat.61.jpg',
 'cat.109.jpg',
 'cat.78.jpg',
 'cat.87.jpg',
 'cat.72.jpg',
 'cat.66.jpg',
 'cat.76.jpg',
 'cat.96.jpg',
 'cat.117.jpg',
 'cat.116.jpg',
 'cat.35.jpg',
 'cat.37.jpg',
 'cat.112.jpg',
 'cat.118.jpg',
 'cat.85.jpg',
 'cat.99.jpg',
 'cat.36.jpg',
 'cat.50.jpg',
 'cat.44.jpg',
 'cat.111.jpg',
 'cat.115.jpg',
 'cat.102.jpg',
 'cat.51.jpg',
 'cat.68.jpg',
 'cat.93.jpg',
 'cat.84.jpg',
 'cat.70.jpg',
 'cat.119.jpg',
 'cat.55.jpg',
 'cat.88.jpg',
 'cat.45.jpg',
 'cat.95.jpg',
 'cat.114.jpg',
 'cat.81.jpg',
 'cat.60.jpg',
 'cat.38.jpg',
 'cat.92.jpg',
 'cat.79.jpg',
 'cat.89.jpg',
 'cat.105.jpg',
 'cat.110.jpg',
 'cat.40.jpg',
 'cat.46.jpg',
 'cat.63.jpg',
 'cat.53.jpg',
 'cat.74.jpg',
 'cat.59.jpg',
 'cat.54.jpg',
 'cat.73.jpg',
 'cat.98.jpg',
 'cat.58.jpg',
 'cat.71.jpg',
 'cat.75.jpg',
 'cat.57.jpg',
 'cat.101.jp

In [52]:
os.listdir('/content/drive/MyDrive/Data_cnn/Dog')

['dog.59.jpg',
 'dog.48.jpg',
 'dog.39.jpg',
 'dog.54.jpg',
 'dog.45.jpg',
 'dog.28.jpg',
 'dog.15.jpg',
 'dog.14.jpg',
 'dog.35.jpg',
 'dog.41.jpg',
 'dog.33.jpg',
 'dog.27.jpg',
 'dog.19.jpg',
 'dog.46.jpg',
 'dog.49.jpg',
 'dog.67.jpg',
 'dog.47.jpg',
 'dog.36.jpg',
 'dog.64.jpg',
 'dog.38.jpg',
 'dog.8.jpg',
 'dog.21.jpg',
 'dog.60.jpg',
 'dog.26.jpg',
 'dog.63.jpg',
 'dog.65.jpg',
 'dog.53.jpg',
 'dog.1.jpg',
 'dog.32.jpg',
 'dog.37.jpg',
 'dog.68.jpg',
 'dog.11.jpg',
 'dog.17.jpg',
 'dog.52.jpg',
 'dog.20.jpg',
 'dog.13.jpg',
 'dog.23.jpg',
 'dog.66.jpg',
 'dog.34.jpg',
 'dog.3.jpg',
 'dog.61.jpg',
 'dog.18.jpg',
 'dog.58.jpg',
 'dog.43.jpg',
 'dog.57.jpg',
 'dog.51.jpg',
 'dog.56.jpg',
 'dog.10.jpg',
 'dog.6.jpg',
 'dog.42.jpg',
 'dog.31.jpg',
 'dog.9.jpg',
 'dog.22.jpg',
 'dog.5.jpg',
 'dog.12.jpg',
 'dog.44.jpg',
 'dog.24.jpg',
 'dog.4.jpg',
 'dog.30.jpg',
 'dog.50.jpg',
 'dog.55.jpg',
 'dog.62.jpg',
 'dog.16.jpg',
 'dog.29.jpg',
 'dog.40.jpg',
 'dog.2.jpg',
 'dog.7.jpg',
 'do

In [53]:
len(os.listdir('/content/drive/MyDrive/Data_cnn/Cat'))

85

In [54]:
len(os.listdir('/content/drive/MyDrive/Data_cnn/Dog'))

68

In [55]:
#path join

#catpath

#Data  : '/content/drive/mydrive/data cat

#Join

catpath=os.path.join('/content/drive/MyDrive/Data_cnn','Cat')
for img in os.listdir(catpath):
  print(img)

cat.82.jpg
cat.48.jpg
cat.67.jpg
cat.97.jpg
cat.103.jpg
cat.56.jpg
cat.69.jpg
cat.94.jpg
cat.80.jpg
cat.86.jpg
cat.39.jpg
cat.61.jpg
cat.109.jpg
cat.78.jpg
cat.87.jpg
cat.72.jpg
cat.66.jpg
cat.76.jpg
cat.96.jpg
cat.117.jpg
cat.116.jpg
cat.35.jpg
cat.37.jpg
cat.112.jpg
cat.118.jpg
cat.85.jpg
cat.99.jpg
cat.36.jpg
cat.50.jpg
cat.44.jpg
cat.111.jpg
cat.115.jpg
cat.102.jpg
cat.51.jpg
cat.68.jpg
cat.93.jpg
cat.84.jpg
cat.70.jpg
cat.119.jpg
cat.55.jpg
cat.88.jpg
cat.45.jpg
cat.95.jpg
cat.114.jpg
cat.81.jpg
cat.60.jpg
cat.38.jpg
cat.92.jpg
cat.79.jpg
cat.89.jpg
cat.105.jpg
cat.110.jpg
cat.40.jpg
cat.46.jpg
cat.63.jpg
cat.53.jpg
cat.74.jpg
cat.59.jpg
cat.54.jpg
cat.73.jpg
cat.98.jpg
cat.58.jpg
cat.71.jpg
cat.75.jpg
cat.57.jpg
cat.101.jpg
cat.64.jpg
cat.107.jpg
cat.90.jpg
cat.113.jpg
cat.42.jpg
cat.62.jpg
cat.43.jpg
cat.91.jpg
cat.108.jpg
cat.83.jpg
cat.41.jpg
cat.52.jpg
cat.49.jpg
cat.106.jpg
cat.47.jpg
cat.65.jpg
cat.77.jpg
cat.104.jpg
cat.100.jpg


In [56]:
dogpath=os.path.join('/content/drive/MyDrive/Data_cnn','Dog')
for img in os.listdir(dogpath):
  print(img)

dog.59.jpg
dog.48.jpg
dog.39.jpg
dog.54.jpg
dog.45.jpg
dog.28.jpg
dog.15.jpg
dog.14.jpg
dog.35.jpg
dog.41.jpg
dog.33.jpg
dog.27.jpg
dog.19.jpg
dog.46.jpg
dog.49.jpg
dog.67.jpg
dog.47.jpg
dog.36.jpg
dog.64.jpg
dog.38.jpg
dog.8.jpg
dog.21.jpg
dog.60.jpg
dog.26.jpg
dog.63.jpg
dog.65.jpg
dog.53.jpg
dog.1.jpg
dog.32.jpg
dog.37.jpg
dog.68.jpg
dog.11.jpg
dog.17.jpg
dog.52.jpg
dog.20.jpg
dog.13.jpg
dog.23.jpg
dog.66.jpg
dog.34.jpg
dog.3.jpg
dog.61.jpg
dog.18.jpg
dog.58.jpg
dog.43.jpg
dog.57.jpg
dog.51.jpg
dog.56.jpg
dog.10.jpg
dog.6.jpg
dog.42.jpg
dog.31.jpg
dog.9.jpg
dog.22.jpg
dog.5.jpg
dog.12.jpg
dog.44.jpg
dog.24.jpg
dog.4.jpg
dog.30.jpg
dog.50.jpg
dog.55.jpg
dog.62.jpg
dog.16.jpg
dog.29.jpg
dog.40.jpg
dog.2.jpg
dog.7.jpg
dog.25.jpg


In [57]:
flat_data_arr=[] #To collect input
target_arr=[] #To collect output
categories=['Cat','Dog']
datadir='/content/drive/MyDrive/Data_cnn'

In [58]:
for i in categories:
  print("Loading catagories........")
  path=os.path.join(datadir,i)
  for img in os.listdir(path):
    img_arr=imread(os.path.join(path,img))
    img_resize=resize(img_arr,(150,150,3))
    flat_data_arr.append(img_resize.flatten())#Linear data
    target_arr.append(categories.index(i))
  print("Loaded completely",i)

Loading catagories........
Loaded completely Cat
Loading catagories........
Loaded completely Dog


In [59]:
flat_data_arr

[array([0.47829514, 0.47437357, 0.49790298, ..., 0.54186833, 0.50657421,
        0.51049578]),
 array([0.30199647, 0.61572196, 0.27454549, ..., 0.55087582, 0.54134641,
        0.50530719]),
 array([0.74680098, 0.66483396, 0.5706102 , ..., 0.57267973, 0.51340612,
        0.48596613]),
 array([0.47976095, 0.36642162, 0.32647723, ..., 0.40213642, 0.42617976,
        0.48892486]),
 array([0.60196092, 0.6176472 , 0.61372563, ..., 0.69056703, 0.68987585,
        0.6892917 ]),
 array([0.22265035, 0.03049349, 0.1050033 , ..., 0.35145011, 0.35929324,
        0.3536187 ]),
 array([0.15289102, 0.16073416, 0.14112632, ..., 0.48522976, 0.47336046,
        0.40042588]),
 array([0.26886684, 0.20380723, 0.17081279, ..., 0.83349797, 0.77859601,
        0.66487052]),
 array([0.30229051, 0.29444737, 0.21209443, ..., 0.58856487, 0.57287859,
        0.52581977]),
 array([0.56470588, 0.57254902, 0.52156863, ..., 0.16218986, 0.13473888,
        0.09883247]),
 array([0.0610811 , 0.06500267, 0.0728458 , ..., 0

In [60]:
target_arr

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1]

In [61]:
flat_data=np.array(flat_data_arr)
target_data=np.array(target_arr)

df=pd.DataFrame(flat_data)
df
#

0         1         2         3         4         5         6      \
0    0.478295  0.474374  0.497903  0.477381  0.473460  0.496989  0.491041   
1    0.301996  0.615722  0.274545  0.290050  0.603775  0.262599  0.292481   
2    0.746801  0.664834  0.570610  0.768159  0.669622  0.570784  0.766071   
3    0.479761  0.366422  0.326477  0.497796  0.378511  0.336458  0.519553   
4    0.601961  0.617647  0.613726  0.604402  0.620088  0.616167  0.597635   
..        ...       ...       ...       ...       ...       ...       ...   
148  0.685722  0.646506  0.368075  0.699454  0.660238  0.381807  0.698172   
149  0.131540  0.185830  0.340608  0.146411  0.201307  0.354267  0.161383   
150  0.720659  0.608868  0.484345  0.788838  0.698053  0.589112  0.699704   
151  0.078935  0.086778  0.075013  0.082741  0.090585  0.078820  0.097564   
152  0.008784  0.081797  0.003346  0.041734  0.105453  0.029321  0.048398   

        7         8         9      ...     67490     67491     67492  \
0    0.487119  0.510649  0.499533  ...  0.544947  0.576333  0.541039   
1    0.597207  0.270827  0.309201  ...  0.486623  0.526157  0.516627   
2    0.672205  0.569096  0.722603  ...  0.414763  0.622804  0.523688   
3    0.389613  0.342338  0.524326  ...  0.498604  0.431083  0.458534   
4    0.613321  0.609399  0.596407  ...  0.680711  0.632742  0.635138   
..        ...       ...       ...  ...       ...       ...       ...   
148  0.658956  0.380525  0.702169  ...  0.255720  0.279402  0.255875   
149  0.223393  0.366578  0.169894  ...  0.118748  0.093208  0.023828   
150  0.640619  0.565847  0.694656  ...  0.761163  0.802625  0.783017   
151  0.105407  0.093643  0.116938  ...  0.505489  0.518806  0.530571   
152  0.092893  0.028838  0.081621  ...  0.042053  0.384837  0.333710   

        67493     67494     67495     67496     67497     67498     67499  
0    0.544960  0.562095  0.526801  0.530722  0.541868  0.506574  0.510496  
1    0.480588  0.537490  0.527961  0.491922  0.550876  0.541346  0.505307  
2    0.484664  0.575169  0.504724  0.476907  0.572680  0.513406  0.485966  
3    0.521279  0.413828  0.441070  0.503815  0.402136  0.426180  0.488925  
4    0.645287  0.631576  0.633479  0.642293  0.690567  0.689876  0.689292  
..        ...       ...       ...       ...       ...       ...       ...  
148  0.255872  0.287548  0.264846  0.262367  0.276438  0.256726  0.245274  
149  0.017193  0.134098  0.063522  0.055692  0.102538  0.033174  0.026556  
150  0.759488  0.796551  0.776943  0.753413  0.797203  0.777595  0.754066  
151  0.550179  0.496733  0.508497  0.528105  0.494269  0.506033  0.525641  
152  0.030124  0.388362  0.344401  0.031503  0.377621  0.327669  0.020758  

[153 rows x 67500 columns]

In [62]:
df.shape

(153, 67500)

In [63]:
df['Target']=target_data


In [64]:
df.shape

(153, 67501)

In [65]:
df

0         1         2         3         4         5         6  \
0    0.478295  0.474374  0.497903  0.477381  0.473460  0.496989  0.491041   
1    0.301996  0.615722  0.274545  0.290050  0.603775  0.262599  0.292481   
2    0.746801  0.664834  0.570610  0.768159  0.669622  0.570784  0.766071   
3    0.479761  0.366422  0.326477  0.497796  0.378511  0.336458  0.519553   
4    0.601961  0.617647  0.613726  0.604402  0.620088  0.616167  0.597635   
..        ...       ...       ...       ...       ...       ...       ...   
148  0.685722  0.646506  0.368075  0.699454  0.660238  0.381807  0.698172   
149  0.131540  0.185830  0.340608  0.146411  0.201307  0.354267  0.161383   
150  0.720659  0.608868  0.484345  0.788838  0.698053  0.589112  0.699704   
151  0.078935  0.086778  0.075013  0.082741  0.090585  0.078820  0.097564   
152  0.008784  0.081797  0.003346  0.041734  0.105453  0.029321  0.048398   

            7         8         9  ...     67491     67492     67493  \
0    0.487119  0.510649  0.499533  ...  0.576333  0.541039  0.544960   
1    0.597207  0.270827  0.309201  ...  0.526157  0.516627  0.480588   
2    0.672205  0.569096  0.722603  ...  0.622804  0.523688  0.484664   
3    0.389613  0.342338  0.524326  ...  0.431083  0.458534  0.521279   
4    0.613321  0.609399  0.596407  ...  0.632742  0.635138  0.645287   
..        ...       ...       ...  ...       ...       ...       ...   
148  0.658956  0.380525  0.702169  ...  0.279402  0.255875  0.255872   
149  0.223393  0.366578  0.169894  ...  0.093208  0.023828  0.017193   
150  0.640619  0.565847  0.694656  ...  0.802625  0.783017  0.759488   
151  0.105407  0.093643  0.116938  ...  0.518806  0.530571  0.550179   
152  0.092893  0.028838  0.081621  ...  0.384837  0.333710  0.030124   

        67494     67495     67496     67497     67498     67499  Target  
0    0.562095  0.526801  0.530722  0.541868  0.506574  0.510496       0  
1    0.537490  0.527961  0.491922  0.550876  0.541346  0.505307       0  
2    0.575169  0.504724  0.476907  0.572680  0.513406  0.485966       0  
3    0.413828  0.441070  0.503815  0.402136  0.426180  0.488925       0  
4    0.631576  0.633479  0.642293  0.690567  0.689876  0.689292       0  
..        ...       ...       ...       ...       ...       ...     ...  
148  0.287548  0.264846  0.262367  0.276438  0.256726  0.245274       1  
149  0.134098  0.063522  0.055692  0.102538  0.033174  0.026556       1  
150  0.796551  0.776943  0.753413  0.797203  0.777595  0.754066       1  
151  0.496733  0.508497  0.528105  0.494269  0.506033  0.525641       1  
152  0.388362  0.344401  0.031503  0.377621  0.327669  0.020758       1  

[153 rows x 67501 columns]

In [66]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]


In [67]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20)

In [68]:
from sklearn.svm import SVC
model=SVC()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1])

In [69]:
from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy Score",accuracy_score(y_pred,y_test))

Accuracy Score 0.5806451612903226


In [70]:
path1='/content/drive/MyDrive/cat1.jpeg'
img=imread(path1)
img=resize(img,(150,150,3)).flatten().reshape(1,-1)
model.predict(img)

array([0])

In [71]:
path2='/content/drive/MyDrive/dog1.jpeg'
img=imread(path2)
img=resize(img,(150,150,3)).flatten().reshape(1,-1)
model.predict(img)

array([1])