<a href="https://colab.research.google.com/github/AshlinShaji/DL/blob/main/Mask_detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [45]:
from google.colab import drive
drive.mount('/content/drive')
#

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [46]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
from sklearn.svm import SVC
from skimage.io import imread
from sklearn.model_selection import train_test_split
from skimage.transform import resize

In [47]:
os.listdir('/content/drive/MyDrive/data imgcla')

['WithoutMask', 'WithMask']

In [48]:
os.listdir('/content/drive/MyDrive/data imgcla/WithMask')

['Augmented_272_3768963.png',
 'Augmented_698_2753022.png',
 '1439.png',
 '1565.png',
 '1388.png',
 '1834.png',
 '1835.png',
 '147.png',
 '1612.png',
 '3.png',
 '1405.png',
 '190.png',
 '1389.png',
 '187.png',
 '1174.png',
 '1820.png',
 '1836.png',
 '1407.png',
 '230.png',
 '1163.png',
 '231.png',
 '224.png',
 '152.png',
 '350.png',
 '1175.png',
 '1203.png',
 '219.png',
 '1606.png',
 '1363.png',
 '225.png',
 '1362.png',
 '1607.png',
 '1404.png',
 '1558.png',
 '1559.png',
 '1573.png',
 '1821.png',
 '1361.png',
 '1767.png',
 '153.png',
 '1413.png',
 '178.png',
 '1611.png',
 'Augmented_229_8982593.png',
 'Augmented_19_9334896.png',
 'Augmented_346_6949456.png',
 'Augmented_309_2910491.png',
 'Augmented_507_2627970.png',
 'Augmented_268_6102153.png',
 'Augmented_133_8515405.png',
 'Augmented_214_4163448.png',
 'Augmented_559_2684759.png',
 'Augmented_297_6884580.png',
 'Augmented_349_6184398.png',
 'Augmented_258_734349.png',
 'Augmented_320_4942257.png',
 'Augmented_115_6749830.png',
 'Au

In [49]:
os.listdir('/content/drive/MyDrive/data imgcla/WithoutMask')

['1983.png',
 '2051.png',
 '344.png',
 '5702.png',
 '5688.png',
 '5677.png',
 '5715.png',
 '1001.png',
 '1201.png',
 '1767.png',
 '2050.png',
 '1567.png',
 '1161.png',
 '1177.png',
 '1570.png',
 '1996.png',
 '1163.png',
 '1940.png',
 '1349.png',
 '1639.png',
 '150.png',
 '1607.png',
 '1968.png',
 '152.png',
 '1969.png',
 '1174.png',
 '1613.png',
 '1773.png',
 '1215.png',
 '2078.png',
 '1772.png',
 '1175.png',
 '178.png',
 '1836.png',
 '1565.png',
 '191.png',
 '1388.png',
 '1217.png',
 '1982.png',
 '1820.png',
 '1573.png',
 '1029.png',
 '2087.png',
 '1439.png',
 '1015.png',
 '153.png',
 '146.png',
 '147.png',
 '193.png',
 '2044.png',
 '1834.png',
 '1413.png',
 '1798.png',
 '144.png',
 '1411.png',
 '1558.png',
 '1160.png',
 '1559.png',
 '1203.png',
 '184.png',
 '2052.png',
 '2091.png',
 '1407.png',
 '1997.png',
 '1835.png',
 '1188.png',
 '1405.png',
 '1361.png',
 '2086.png',
 '1377.png',
 '187.png',
 '1941.png',
 '1822.png',
 '1438.png',
 '1821.png',
 '1605.png',
 '1014.png',
 '1149.png'

In [50]:
len(os.listdir('/content/drive/MyDrive/data imgcla/WithMask'))

483

In [51]:
len(os.listdir('/content/drive/MyDrive/data imgcla/WithoutMask'))

509

In [52]:
maskpath=os.path.join('/content/drive/MyDrive/data imgcla','WithMask')
for img in os.listdir(maskpath):
  print(img)

Augmented_272_3768963.png
Augmented_698_2753022.png
1439.png
1565.png
1388.png
1834.png
1835.png
147.png
1612.png
3.png
1405.png
190.png
1389.png
187.png
1174.png
1820.png
1836.png
1407.png
230.png
1163.png
231.png
224.png
152.png
350.png
1175.png
1203.png
219.png
1606.png
1363.png
225.png
1362.png
1607.png
1404.png
1558.png
1559.png
1573.png
1821.png
1361.png
1767.png
153.png
1413.png
178.png
1611.png
Augmented_229_8982593.png
Augmented_19_9334896.png
Augmented_346_6949456.png
Augmented_309_2910491.png
Augmented_507_2627970.png
Augmented_268_6102153.png
Augmented_133_8515405.png
Augmented_214_4163448.png
Augmented_559_2684759.png
Augmented_297_6884580.png
Augmented_349_6184398.png
Augmented_258_734349.png
Augmented_320_4942257.png
Augmented_115_6749830.png
Augmented_161_3678243.png
Augmented_144_2572190.png
Augmented_105_2237800.png
Augmented_211_1296894.png
Augmented_153_259583.png
Augmented_530_6846848.png
Augmented_328_7802777.png
Augmented_275_4307929.png
Augmented_440_5403192.png

In [53]:
maskpath=os.path.join('/content/drive/MyDrive/data imgcla','WithoutMask')
for img in os.listdir(maskpath):
  print(img)

1983.png
2051.png
344.png
5702.png
5688.png
5677.png
5715.png
1001.png
1201.png
1767.png
2050.png
1567.png
1161.png
1177.png
1570.png
1996.png
1163.png
1940.png
1349.png
1639.png
150.png
1607.png
1968.png
152.png
1969.png
1174.png
1613.png
1773.png
1215.png
2078.png
1772.png
1175.png
178.png
1836.png
1565.png
191.png
1388.png
1217.png
1982.png
1820.png
1573.png
1029.png
2087.png
1439.png
1015.png
153.png
146.png
147.png
193.png
2044.png
1834.png
1413.png
1798.png
144.png
1411.png
1558.png
1160.png
1559.png
1203.png
184.png
2052.png
2091.png
1407.png
1997.png
1835.png
1188.png
1405.png
1361.png
2086.png
1377.png
187.png
1941.png
1822.png
1438.png
1821.png
1605.png
1014.png
1149.png
1363.png
1410.png
1404.png
185.png
1148.png
1955.png
1571.png
1376.png
1202.png
1606.png
1362.png
1564.png
1799.png
1808.png
190.png
1954.png
1611.png
2085.png
1000.png
1612.png
1766.png
1.png
1216.png
1809.png
1375.png
1598.png
2045.png
1028.png
2079.png
3831.png
2654.png
4972.png
4385.png
46.png
4742.png
39

In [54]:
flat_data_arr=[]
target_arr=[]
categories=['WithMask','WithoutMask']
datadir='/content/drive/MyDrive/data imgcla'

In [55]:
for i in categories:
  print("Loading categories..........")
  path=os.path.join(datadir,i)
  for img in os.listdir(path):
    img_arr=imread(os.path.join(path,img))
    img_resize=resize(img_arr,(150,150,3))
    flat_data_arr.append(img_resize.flatten())
    target_arr.append(categories.index(i))
  print("Loaded Completely",i)

Loading categories..........
Loaded Completely WithMask
Loading categories..........
Loaded Completely WithoutMask


In [56]:
flat_data_arr

[array([0.41960595, 0.41960595, 0.41960595, ..., 0.2274515 , 0.2274515 ,
        0.2274515 ]),
 array([0.05098039, 0.06666667, 0.09411765, ..., 0.73725901, 0.58431784,
        0.45490575]),
 array([0.07001307, 0.0660915 , 0.05057394, ..., 0.07566013, 0.09918954,
        0.1540915 ]),
 array([0.51330026, 0.44174898, 0.39517168, ..., 0.38775377, 0.37206749,
        0.33677338]),
 array([0.16665712, 0.12277952, 0.0706488 , ..., 0.75327508, 0.63783359,
        0.51043015]),
 array([0.88591285, 0.81146841, 0.75720806, ..., 0.53268845, 0.41752505,
        0.30351416]),
 array([0.51410754, 0.49584941, 0.49153882, ..., 0.33500375, 0.23883712,
        0.23882736]),
 array([0.63208863, 0.56123412, 0.50573569, ..., 0.47192824, 0.40772392,
        0.42853098]),
 array([0.01254902, 0.00392157, 0.        , ..., 0.01192157, 0.00784314,
        0.03686275]),
 array([0.35203813, 0.30507878, 0.30718601, ..., 0.15377756, 0.1318037 ,
        0.16822976]),
 array([0.93333333, 0.93333333, 0.93333333, ..., 0

In [57]:
 target_arr

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,


In [58]:
flat_data=np.array(flat_data_arr)
target_data=np.array(target_arr)

df=pd.DataFrame(flat_data)
df['Target']=target_data
df

0         1         2  ...     67498     67499  Target
0    0.419606  0.419606  0.419606  ...  0.227452  0.227452       0
1    0.050980  0.066667  0.094118  ...  0.584318  0.454906       0
2    0.070013  0.066092  0.050574  ...  0.099190  0.154092       0
3    0.513300  0.441749  0.395172  ...  0.372067  0.336773       0
4    0.166657  0.122780  0.070649  ...  0.637834  0.510430       0
..        ...       ...       ...  ...       ...       ...     ...
987  0.905882  0.847059  0.717647  ...  0.582734  0.494526       1
988  0.127101  0.084954  0.069549  ...  0.646153  0.508159       1
989  0.431065  0.329104  0.184947  ...  0.207799  0.099319       1
990  0.604942  0.584825  0.598472  ...  0.770480  0.783775       1
991  0.556303  0.733270  0.823466  ...  0.104136  0.080607       1

[992 rows x 67501 columns]

In [59]:
df.shape

(992, 67501)

In [60]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]
#

In [61]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20)

In [62]:
model=SVC()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
y_pred

array([1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0])

In [63]:
from sklearn.metrics import accuracy_score
print("Accuracy Score",accuracy_score(y_pred,y_test))

Accuracy Score 0.9246231155778895


In [64]:
path1='/content/drive/MyDrive/wm1.jpeg'
img=imread(path1)
img=resize(img,(150,150,3)).flatten().reshape(1,-1)
model.predict(img)

array([0])

In [65]:
path2='/content/drive/MyDrive/wom1.jpeg'
img=imread(path2)
img=resize(img,(150,150,3)).flatten().reshape(1,-1)
model.predict(img)

array([0])