In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import cmake
import face_recognition as fr
import cv2 

c:\Users\ashli\Documents\DL\.venv\Lib\site-packages\face_recognition_models\__init__.py:7: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import resource_filename


In [2]:
path='images'

In [3]:
os.listdir(path)

['dulquer.jpg', 'mamooty.jpg', 'MESSI.jpg', 'mohanlal.jpg', 'Nivin_Pauly.jpg']

In [4]:
mylist=os.listdir(path)
mylist

['dulquer.jpg', 'mamooty.jpg', 'MESSI.jpg', 'mohanlal.jpg', 'Nivin_Pauly.jpg']

In [5]:
imgs=[]
classnames=[]
for i in mylist:
    imgpath=os.path.join(path,i)
    current_img=cv2.imread(imgpath)
    print(current_img)
    imgs.append(current_img)
    classnames.append(i.split(".")[0])
    


[[[ 37  56  89]
  [ 34  53  86]
  [ 33  52  85]
  ...
  [ 35 107 155]
  [ 36 105 155]
  [ 35 104 154]]

 [[ 36  55  88]
  [ 33  52  85]
  [ 32  51  84]
  ...
  [ 35 107 155]
  [ 37 106 156]
  [ 37 106 156]]

 [[ 35  54  87]
  [ 33  52  85]
  [ 31  50  83]
  ...
  [ 37 106 155]
  [ 39 108 158]
  [ 41 110 160]]

 ...

 [[ 40  72 131]
  [ 37  69 128]
  [ 35  64 125]
  ...
  [ 42  70 104]
  [ 41  69 103]
  [ 42  71 102]]

 [[ 30  68 126]
  [ 31  68 126]
  [ 31  65 125]
  ...
  [ 43  71 106]
  [ 41  69 104]
  [ 41  69 103]]

 [[ 28  68 126]
  [ 30  68 126]
  [ 29  65 125]
  ...
  [ 43  71 106]
  [ 41  69 104]
  [ 41  69 104]]]
[[[123 147 169]
  [123 147 169]
  [123 147 169]
  ...
  [121 145 167]
  [121 145 167]
  [121 145 167]]

 [[123 147 169]
  [123 147 169]
  [123 147 169]
  ...
  [121 145 167]
  [121 145 167]
  [121 145 167]]

 [[123 147 169]
  [123 147 169]
  [123 147 169]
  ...
  [121 145 167]
  [121 145 167]
  [121 145 167]]

 ...

 [[125 149 173]
  [125 149 173]
  [125 149 173]
  ..

In [6]:
#face location and face encoding
def faceencodings(images):
    encodelist=[]
    for img in images:
        img=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
        face_in_frame=fr.face_locations(img)
        print(face_in_frame)
        encoding=fr.face_encodings(img,face_in_frame)[0]#0 to convert to 1d
        encodelist.append(encoding)
    return encodelist



In [7]:
encode_known_face=faceencodings(imgs)
encode_known_face

[(139, 428, 325, 242)]
[(320, 735, 587, 468)]
[(139, 225, 268, 96)]
[(650, 1167, 1316, 502)]
[(167, 340, 390, 117)]


[array([-0.17139609,  0.09028566,  0.05839186, -0.05156002, -0.07988706,
        -0.01428586, -0.00446122, -0.02684591,  0.22020733, -0.11001981,
         0.2452344 ,  0.00309465, -0.20077313, -0.11764299,  0.03009903,
         0.0570363 , -0.1077505 , -0.05722166, -0.04169446, -0.09911419,
         0.05977584,  0.01953432,  0.07056087,  0.05354044, -0.23451059,
        -0.44535902, -0.07929172, -0.13353063, -0.00588493, -0.14340308,
        -0.00911144,  0.03199753, -0.16932267, -0.04653566, -0.03115072,
         0.06501632, -0.01365372, -0.03038337,  0.14898856,  0.00871254,
        -0.15814377, -0.05509453,  0.01559998,  0.27630603,  0.17430858,
        -0.00956191,  0.0639651 , -0.11047722,  0.15673472, -0.17539679,
         0.06663952,  0.1246575 , -0.00081843,  0.0173498 ,  0.12560073,
        -0.07800774,  0.01705918,  0.09352574, -0.20184594,  0.03756854,
         0.0491399 ,  0.05262888, -0.06947398, -0.00199008,  0.16244785,
         0.11004408, -0.11928705, -0.15099877,  0.0

In [9]:
video=cv2.VideoCapture(0)
while True:
    suc,img=video.read()
    img1=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
    face_in_frame=fr.face_locations(img1)
    # print(face_in_frame)
    encoded_face=fr.face_encodings(img1,face_in_frame)
    # print(encoded_face)
    
    for face_loc,enc in zip(face_in_frame,encoded_face):
        matches=fr.compare_faces(encode_known_face,enc)
        face_distance=fr.face_distance(encode_known_face,enc)
        math_index=np.argmin(face_distance)
        if matches[math_index]==True:
            name=classnames[math_index]
            print(name)
            y1,x2,y2,x1=face_loc
            cv2.rectangle(img,(x1,y1),(x2,y2),(0,255,0),2)
            cv2.putText(img,name,(x1,y1-10),cv2.FONT_HERSHEY_SIMPLEX,0.9,(255,0,0),2) 
        


    cv2.imshow('video',img)
    if cv2.waitKey(1) & 0xFF==ord('q'):
        break

video.release()
cv2.destroyAllWindows()

dulquer
dulquer
dulquer
dulquer
dulquer
dulquer


In [ ]:
# fruits=['apple','banana','cherry','date']
# colors=['red','yellow','red','brown']
# print(fruits)
# print(colors)

# # [(apple,red),(banana,yellow),(cherry,red),(date,brown)]
# # (apple,red)
# # (banana,yellow)

# for i,j in zip(fruits,colors):
#     print(i,j)


['apple', 'banana', 'cherry', 'date']
['red', 'yellow', 'red', 'brown']
apple red
banana yellow
cherry red
date brown


In [ ]:
video = cv2.VideoCapture(0)

while True:
    suc, img = video.read()
    if not suc:
        print("Failed to capture video")
        break

    img1 = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    face_in_frame = fr.face_locations(img1)
    encoded_face = fr.face_encodings(img1, face_in_frame)

    for face_loc, enc in zip(face_in_frame, encoded_face):
        matches = fr.compare_faces(encode_known_face, enc)
        face_distance = fr.face_distance(encode_known_face, enc)
        match_index = np.argmin(face_distance)

        y1, x2, y2, x1 = face_loc

        if matches[match_index]:
            name = classnames[match_index]
            print(name)
        else:
            name = "Unknown"
            color = (0, 0, 255)  # Red
            print("Unknown Face")

        cv2.rectangle(img, (x1, y1), (x2, y2), color, 2)
        cv2.putText(img, name, (x1, y1 - 10),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.9, color, 2)

    cv2.imshow('video', img)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

video.release()
cv2.destroyAllWindows()


dulquer
Unknown Face
Unknown Face
dulquer
Unknown Face
Unknown Face
Unknown Face
Unknown Face
dulquer
